name: Deploy to EC2

on:
  push:
    branches:
      - main  # Esto ejecutará el flujo de trabajo al hacer push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}  # Tu llave privada, configurada en Secrets

      - name: Deploy to EC2
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          NATS_SERVERS: ${{ secrets.NATS_SERVERS }}
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.198.163.46 << 'EOF'
            # Instalar Git si no está instalado
            sudo dnf install -y git

            # Navegar al directorio de usuario y clonar el repositorio
            cd /home/ec2-user/
            rm -rf Products-launcher  # Elimina cualquier versión anterior del proyecto
            git clone https://github.com/Kahyberth/Products-launcher.git  # Clona el repositorio de nuevo

            # Cambia al directorio del proyecto clonado
            cd Products-launcher

            # Descargar las últimas versiones de las imágenes de Docker
            docker-compose pull
            # Detener y eliminar contenedores en ejecución
            docker-compose down
            # Levantar los servicios en segundo plano
            docker-compose up -d
          EOF
