name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2 - Git Clone
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.163.50.213 << 'EOF'
            sudo dnf install -y git
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd /home/ec2-user/
            rm -rf Products-launcher
            git clone https://github.com/Kahyberth/Products-launcher.git
          EOF

      - name: Deploy to EC2 - Docker Compose Pull
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.163.50.213 << 'EOF'
            cd /home/ec2-user/Products-launcher
            docker-compose pull
          EOF

      - name: Deploy to EC2 - Docker Compose Down and Up
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.163.50.213 << 'EOF'
            cd /home/ec2-user/Products-launcher
            docker-compose down
            docker-compose up -d
          EOF
