name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          NATS_SERVERS: ${{ secrets.NATS_SERVERS }}
        run: |
          ssh -o ServerAliveInterval=50 -o ServerAliveCountMax=4 -o StrictHostKeyChecking=no ec2-user@18.208.211.181 << 'EOF'
            # Instalar Git si no está instalado
            sudo dnf install -y git

            # Configurar SSH para GitHub y clonar el repositorio
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd /home/ec2-user/
            rm -rf Products-launcher
            git clone https://github.com/Kahyberth/Products-launcher.git

            # Navegar al directorio del proyecto
            cd Products-launcher

            # Actualizar imágenes y levantar servicios en segundo plano
            docker-compose pull
            docker-compose down
            
            # Ejecutar docker-compose up -d en segundo plano
            nohup docker-compose up -d > deploy.log 2>&1 &
          EOF
